name: Build packages
on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build luci-app-singb
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1

      - name: Build and push
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          tags: singb:ci

      - name: Create Docker container
        run: docker create --name singb singb:ci

      - name: Copy file from Docker container
        run: |
          docker cp singb:/builder/bin/packages/x86_64/luci/. ./bin/

      - name: Filter IPK files
        run: |
          # Извлекаем версию из тега, убирая префикс 'v'
          VERSION=${GITHUB_REF#refs/tags/v}

          mkdir -p ./filtered-bin
          cp ./bin/luci-app-singb*.ipk ./filtered-bin/luci-app-singb.ipk

      - name: Remove Docker container
        run: docker rm singb

      - name: Release
        uses: softprops/action-gh-release@v2.0.8
        with:
          files: ./filtered-bin/*.ipk
